[greeter]
theme-name=Arc-Dark
icon-theme-name=Papirus-Dark
font-name=Inter 11
background=/usr/share/blink/desktop/wallpaper/blink-wallpaper.png
user-background=false
clock-format=%H:%M
indicators=~host;~spacer;~clock;~spacer;~session;~power
position=50%,center 50%,center
round-user-image=true
default-user-image=/usr/share/blink/branding/avatar.png
