[greeter]
theme-name=Adwaita-dark
icon-theme-name=Papirus-Dark
font-name=Sans 11
background=/usr/share/backgrounds/blink-wallpaper.png
user-background=false
clock-format=%H:%M
indicators=~host;~spacer;~clock;~spacer;~session;~power
position=50%,center 50%,center
round-user-image=true
